config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/index'
  get 'home/about'
  
  #root 'home#index'
  root 'friends#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not an Authorized action" if @friend.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is Niraj and I love Ruby :)"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <div class="card mb-4">
    <div class="card-body">
      <% if friend.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h4>
          <ul>
            <% friend.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-2">
        <%= form.label :first_name, class: "form-label" %>
        <%= form.text_field :first_name, class: "form-control" %>
      </div>

      <div class="mb-2">
        <%= form.label :last_name, class: "form-label" %>
        <%= form.text_field :last_name, class: "form-control" %>
      </div>

      <div class="mb-2">
        <%= form.label :email, class: "form-label" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="mb-2">
        <%= form.label :phone, class: "form-label" %>
        <%= form.text_field :phone, class: "form-control" %>
      </div>

      <div class="mb-2">
        <%= form.label :"User ID", class: "form-label" %>
        <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", readonly: true, value: current_user.id %>
      </div>
      <div>
        <%= form.submit "Save Changes", class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<style>
  .custom-table th,
  .custom-table td {
    padding: 0.3rem;
    }
  .custom-table th:first-child {
    width: 10%;}
</style>

<div class="bg-light p-1">
  <table class="table table-bordered custom-table">
    <tbody>
      <tr>
        <th>First name:</th>
        <td><%= friend.first_name %></td>
      </tr>
      <tr>
        <th>Last name:</th>
        <td><%= friend.last_name %></td>
      </tr>
      <tr>
        <th>Email:</th>
        <td><%= friend.email %></td>
      </tr>
      <tr>
        <th>Phone:</th>
        <td><%= friend.phone %></td>
      </tr>

    </tbody>
  </table>
</div>

app/views/friends/edit.html.erb
<h2>Editing friend</h2>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend, class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <h1>Friends List</h1>

  <table class="table table-striped table-bordered table-sm table-hover">
    <thead class="table-dark">
      <tr>
        <th>#</th>
        <th> Name </th>
        <th> Email </th>
        <th> Phone </th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% user_friend_count = Hash.new(0) %>
      <% @friends.each_with_index do |friend, index| %>
        <% if friend.user == current_user %>
          <% user_friend_count[friend.user_id] +=1 %>
          <tr>
            <td><%= user_friend_count[friend.user_id] %></td>
            <td><%= link_to friend.first_name+" "+friend.last_name, friend  %> </td>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= button_to 'Delete', friend, method: :delete,class: "btn btn-outline-danger btn-sm" %> </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <br></br>

  <% if user_signed_in? %>
  <%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>
  <% end %>

<% else %>
    <%= raw(render file: 'app/views/home/index.html.erb') %>
<% end %>

app/views/friends/new.html.erb
<h2>Add new friend</h2>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path, class:"btn btn-secondary" %> <br></br>
</div>

app/views/home/_footer.html.erb
<br><br><br> Footer here ... 

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends',home_index_path, class:"navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "about", home_about_path, class:"nav-link" %>
        </li>

               
       <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "add friends", new_friend_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "view friends", friends_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <% else %>
         <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
        
        <% end %>

      </ul>



      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us ...</h1>

<p>
 <%= @about_me%>
</p>

app/views/home/index.html.erb
<h1>Hello Niraj to Ruby on Rails</h1>

app/views/layouts/_alert.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check-circle-fill" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
</svg>

<div class="alert alert-success d-flex align-items-center" role="alert" style="max-width: 100%; max-height: 50px; ">
  <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"  style="width: 1.5rem; height: 1.5rem;">
    <use xlink:href="#check-circle-fill"/></svg>
  <div>
    <%= notice %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    
    <!-- bootstrap ----- -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- ----- -->

    <title>Friends</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  
  <body>
    
    <%= render "home/header" %>
    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>
    <%= yield %>
    <%= render "home/footer" %>

    <!-- bootstrap ----- -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <!-- ----- -->

  </body>
</html>